name: Continuous Integration

on:
  - push

jobs:
  check-linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/checkout@master

      - name: Check linting, formatting
        run: |
          make check-all

  check-multiplatform-builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.13']

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/checkout@master

      - name: Set up Python
        run: |
          uv venv -p ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          make sync

      - name: Verify the distribution can be built
        run: |
          make build-dist

      - name: Run tests
        run: |
          make run-tests
