name: Continuous Integration

on:
  - push

jobs:
  check-linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - name:  Install requirements
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libblas-dev liblapack-dev

      - uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check linting, formatting
        run: |
          make check-all

  check-multiplatform-builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.13']
    steps:
      - name:  Install requirements (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libblas-dev liblapack-dev

      - name:  Install requirements (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -L -o openblas.zip https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.29/OpenBLAS-0.3.29_x64.zip
          mkdir openblas
          cd openblas
          unzip ../openblas.zip
          cd ..
          echo "OPENBLAS_PATH=$(pwd)/openblas" >> $GITHUB_ENV
          echo "PATH=$(pwd)/openblas/lib;$PATH" >> $GITHUB_PATH

      - uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: |
          uv venv -p ${{ matrix.python-version }}

      - name: Install Requirements
        run: |
          make sync

      - name: Verify the distribution can be built
        run: |
          make build-dist

      - name: Run tests
        run: |
          make run-tests
